Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,10 +16,15 @@ jobs:
       run: |
         # Crear directorio .ssh si no existe
         mkdir -p ~/.ssh
-        # Guardar la clave privada
+        # Verificar si la clave privada está definida correctamente
         echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
-        # Verificar el contenido de la clave privada para asegurarse de que se ha cargado correctamente
-        cat ~/.ssh/id_rsa
+        # Verificar la longitud de la clave privada para asegurarse de que se ha cargado correctamente
+        echo "La longitud de la clave privada es: $(wc -c < ~/.ssh/id_rsa)"
+        
+        # Verificar el contenido de la clave privada (solo para depuración)
+        # ADVERTENCIA: no hagas esto en producción, ya que puede mostrar la clave privada en los logs.
+        cat ~/.ssh/id_rsa || echo "Error: No se pudo mostrar el contenido de la clave privada"
+        
         # Dar permisos adecuados a la clave privada
         chmod 600 ~/.ssh/id_rsa
 
