Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,21 +13,21 @@ jobs:
       env:
         SSH_PRIVATE_KEY: ${{ secrets.altitude-ssh }}
       run: |
+        # Crear directorio .ssh si no existe
         mkdir -p ~/.ssh
+        # Guardar la clave privada
         echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
+        # Dar permisos adecuados a la clave privada
         chmod 600 ~/.ssh/id_rsa
-        
-        # Depuración para verificar el valor de HOST
-        echo "Verificando la variable HOST: $HOST"
-        
-        # Verificar la clave SSH de GitHub
-        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
-        # Verificar la clave SSH del servidor DigitalOcean
-        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts || echo "Error al obtener la clave del host"
 
-    - name: Deploy to Digital Ocean
+        # Agregar hosts conocidos (GitHub y DigitalOcean)
+        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
+        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts || echo "Error al obtener la clave del host DigitalOcean"
+
+    - name: Deploy to DigitalOcean
       env:
         HOST: ${{ secrets.HOST }}
         USER: ${{ secrets.user }}
       run: |
-        ssh $USER@$HOST "cd /var/www/html && git pull origin main"
+        # Desactivar verificación de host para evitar errores de SSH
+        ssh -o StrictHostKeyChecking=no $USER@$HOST "cd /var/www/html && git pull origin main"
